use gpui::{App, Hsla, Pixels, hsla, px};
use gpui_component::{Theme, ThemeMode, ThemeTokens};

pub const BG: Hsla = hsla(0.0, 0.0, 0.129_411_77, 1.0);
pub const SURFACE: Hsla = hsla(0.0, 0.0, 0.156_862_75, 1.0);
pub const RAISED: Hsla = hsla(0.0, 0.0, 0.168_627_46, 1.0);
pub const BORDER: Hsla = hsla(0.0, 0.0, 0.219_607_84, 1.0);
pub const TEXT: Hsla = hsla(0.0, 0.0, 0.925_490_2, 1.0);
pub const MUTED: Hsla = hsla(0.0, 0.0, 0.627_451, 1.0);
pub const ACCENT: Hsla = hsla(0.626_984_1, 0.818_181_8, 0.849_019_6, 1.0);
pub const ATTENTION: Hsla = hsla(0.102_981_03, 0.605_911_3, 0.601_960_8, 1.0);
pub const DANGER: Hsla = hsla(0.994_152_07, 0.655_172_4, 0.658_823_55, 1.0);
pub const SUCCESS: Hsla = hsla(0.419_230_76, 0.541_666_7, 0.529_411_8, 1.0);
pub const CHROME: Hsla = hsla(0.0, 0.0, 0.098_039_22, 1.0);
pub const HOVER: Hsla = hsla(0.0, 0.0, 0.188_235_3, 1.0);
pub const TEXT_SOFT: Hsla = hsla(0.0, 0.0, 0.815_686_3, 1.0);
pub const FAINT: Hsla = hsla(0.0, 0.0, 0.568_627_5, 1.0);

pub const BODY_FONT: &str = "Inter";
pub const MONO_FONT: &str = "IBM Plex Mono";
pub const RADIUS_SMALL: Pixels = px(5.0);
pub const RADIUS_MEDIUM: Pixels = px(8.0);
pub const TRANSCRIPT_WIDTH: Pixels = px(820.0);

pub fn apply(cx: &mut App) {
    let theme = Theme::global_mut(cx);

    theme.mode = ThemeMode::Dark;
    theme.font_family = BODY_FONT.into();
    theme.font_size = px(14.0);
    theme.mono_font_family = MONO_FONT.into();
    theme.mono_font_size = px(12.0);
    theme.radius = RADIUS_SMALL;
    theme.radius_lg = RADIUS_MEDIUM;
    theme.shadow = false;
    theme.focus_ring = true;

    let colors = &mut theme.colors;
    colors.accent = HOVER;
    colors.accent_foreground = TEXT;
    colors.accordion = RAISED;
    colors.background = BG;
    colors.border = BORDER;
    colors.button = SURFACE;
    colors.button_active = RAISED;
    colors.button_foreground = TEXT;
    colors.button_hover = HOVER;
    colors.button_primary = ACCENT;
    colors.button_primary_active = ACCENT.opacity(0.82);
    colors.button_primary_foreground = CHROME;
    colors.button_primary_hover = ACCENT.opacity(0.9);
    colors.button_danger = DANGER;
    colors.button_danger_active = DANGER.opacity(0.82);
    colors.button_danger_foreground = CHROME;
    colors.button_danger_hover = DANGER.opacity(0.9);
    colors.button_success = SUCCESS;
    colors.button_success_active = SUCCESS.opacity(0.82);
    colors.button_success_foreground = CHROME;
    colors.button_success_hover = SUCCESS.opacity(0.9);
    colors.button_warning = ATTENTION;
    colors.button_warning_active = ATTENTION.opacity(0.82);
    colors.button_warning_foreground = CHROME;
    colors.button_warning_hover = ATTENTION.opacity(0.9);
    colors.caret = TEXT;
    colors.danger = DANGER;
    colors.danger_active = DANGER.opacity(0.82);
    colors.danger_foreground = CHROME;
    colors.danger_hover = DANGER.opacity(0.9);
    colors.input = BORDER;
    colors.link = ACCENT;
    colors.link_active = TEXT_SOFT;
    colors.link_hover = TEXT;
    colors.muted = RAISED;
    colors.muted_foreground = MUTED;
    colors.popover = SURFACE;
    colors.popover_foreground = TEXT;
    colors.primary = ACCENT;
    colors.primary_active = ACCENT.opacity(0.82);
    colors.primary_foreground = CHROME;
    colors.primary_hover = ACCENT.opacity(0.9);
    colors.ring = ACCENT;
    colors.secondary = RAISED;
    colors.secondary_active = BORDER;
    colors.secondary_foreground = TEXT;
    colors.secondary_hover = HOVER;
    colors.selection = ACCENT.opacity(0.35);
    colors.sidebar = CHROME;
    colors.sidebar_accent = HOVER;
    colors.sidebar_foreground = TEXT;
    colors.success = SUCCESS;
    colors.success_active = SUCCESS.opacity(0.82);
    colors.success_foreground = CHROME;
    colors.success_hover = SUCCESS.opacity(0.9);
    colors.title_bar = CHROME;
    colors.title_bar_border = BORDER;
    colors.status_bar = CHROME;
    colors.status_bar_border = BORDER;
    colors.warning = ATTENTION;
    colors.warning_active = ATTENTION.opacity(0.82);
    colors.warning_foreground = CHROME;
    colors.warning_hover = ATTENTION.opacity(0.9);
    theme.tokens = ThemeTokens::from(theme.colors);

    Theme::sync_base(cx);
}
