[package]
name = "kiln-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde_json = { workspace = true, features = ["float_roundtrip"] }
sha2.workspace = true
tokio.workspace = true
ulid.workspace = true
url = "=2.5.8"

[dev-dependencies]
tokio.workspace = true
