[package]
name = "kiln-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
kiln-core = { path = "../core" }
kiln-protocol = { path = "../protocol" }
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
